export const ADD_ORDER = 'ADD_ORDER';
export const SET_ORDER = 'SET_ORDER';
export const CHECK_PROMO = 'CHECK_PROMO';
export const SET_NOFI = 'SET_NOFI';
export const REMOVE_NOFI = 'REMOVE_NOFI';

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY'; 
export const CHANGE_PRODUCT_SELECTED = 'CHANGE_PRODUCT_SELECTED'; 